services:
  - type: web
    name: media-downloader-backend
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
